apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      args:
        - sleep
        - "1000000"