apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
spec:
  containers:
    - name: busybox
      image: {{ .Values.app.image.registry }}/busybox:1.28
      args:
        - sleep
        - "1000000"