{{ if .Values.mon.prometheus.install -}}
{{ $Name := printf "%s-%s" .Release.Name .Chart.Name }}
{{ $Alerting := .Values.mon.prometheus.alerting }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
  name: {{ $Name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: {{ $Name }}
      rules:
        - alert: WebSvcMemoryUsage
          expr: web_svc_memory_usage_ratio{job="{{ $Name }}"} > {{ $Alerting.memoryUsage.thresholdRatio }}
          for: {{ $Alerting.memoryUsage.periodSeconds }}s
          labels:
            severity: page
          annotations:
            summary: "Instance {{`{{`}} $labels.instance {{`}}`}} high memory usage"
            description: "{{`{{`}} $labels.instance {{`}}`}} of job {{`{{`}} $labels.job {{`}}`}} has moderately high memory usage for more than {{ $Alerting.memoryUsage.periodSeconds }} seconds."
        - alert: WebSvcNodejsEventloopLag
          expr: nodejs_eventloop_lag_seconds{job="{{ $Name }}"} > {{ $Alerting.eventloopLag.thresholdSeconds }}
          for: {{ $Alerting.eventloopLag.periodSeconds }}s
          labels:
            severity: page
          annotations:
            summary: "Instance {{`{{`}} $labels.instance {{`}}`}} high nodejs eventloop lag"
            description: "{{`{{`}} $labels.instance {{`}}`}} of job {{`{{`}} $labels.job {{`}}`}} has moderately high eventloop lag  for more than {{ $Alerting.eventloopLag.periodSeconds }} seconds."
        - alert: WebSvcProcessCpuUsage
          expr: web_svc_process_cpu_usage_ratio{job="{{ $Name }}"} > {{ $Alerting.cpuUsage.thresholdRatio }}
          for: {{ $Alerting.cpuUsage.periodSeconds }}s
          labels:
            severity: page
          annotations:
            summary: "Instance {{`{{`}} $labels.instance {{`}}`}} high process CPU usage"
            description: "{{`{{`}} $labels.instance {{`}}`}} of job {{`{{`}} $labels.job {{`}}`}} has moderately high CPU usage for more than {{ $Alerting.cpuUsage.periodSeconds }} seconds."
        - alert: WebSvcCpuCfsThrottled
          expr: rate(container_cpu_cfs_throttled_periods_total{pod=~"{{$Name}}.*"}[{{ $Alerting.cpuCfsThrottled.periodSeconds }}s])/rate(container_cpu_cfs_periods_total{pod=~"{{$Name}}..*"}[{{ $Alerting.cpuCfsThrottled.periodSeconds }}s]) > {{ $Alerting.cpuCfsThrottled.thresholdRatio }}
          for: {{ $Alerting.cpuCfsThrottled.periodSeconds }}s
          labels:
            severity: page
          annotations:
            summary: "Instance {{`{{`}} $labels.instance {{`}}`}} container CPU CFS throttled"
            description: "{{`{{`}} $labels.instance {{`}}`}} of job {{`{{`}} $labels.job {{`}}`}} has moderately high container CPU CFS throttled for more than {{ $Alerting.cpuUsage.periodSeconds }} seconds."
        - alert: WebSvcHttpRequestDuration
          expr: web_svc_http_request_duration_seconds{job="{{ $Name }}",quantile="{{ $Alerting.httpRequestDuration.quantile }}"} > {{ $Alerting.httpRequestDuration.thresholdSeconds }}
          for: {{ $Alerting.httpRequestDuration.periodSeconds }}s
          labels:
            severity: page
          annotations:
            summary: "Instance {{`{{`}} $labels.instance {{`}}`}} container http request duration"
            description: "{{`{{`}} $labels.instance {{`}}`}} of job {{`{{`}} $labels.job {{`}}`}} has moderately HTTP request duration for more than {{ $Alerting.httpRequestDuration.periodSeconds }} seconds."
{{- end }}
