{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" . }}
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ include "name" . }}
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: {{ include "name" . }}
  progressDeadlineSeconds: {{ .Values.canary.progressDeadlineSeconds }}
  service:
    port: {{ .Values.app.service.port }}
    targetPort: 3000
  analysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
    - name:  {{ include "CanaryAnalysisHttpSuccessRateMetricName" . }}
      thresholdRange:
        min: {{ .Values.canary.analysis.metrics.httpRequestSuccessRate.thresholdRange.min }}
      interval: {{ .Values.canary.analysis.metrics.httpRequestSuccessRate.interval }}
{{- end }}
