{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: nginx
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name" . }}
  # ingress reference
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ include "name" . }}
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: {{ include "name" . }}
  progressDeadlineSeconds: {{ .Values.canary.progressDeadlineSeconds }}
  service:
    port: {{ .Values.app.service.port }}
    targetPort: 3000
  analysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
    - name: WebSvcRequestSuccessRate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: {{ .Values.canary.analysis.metrics.WebSvcRequestSuccessRate.thresholdRange.min }}
      interval: {{ .Values.canary.analysis.metrics.WebSvcRequestSuccessRate.interval }}
{{- end }}
