apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      imagePullSecrets:{{- range .Values.infra.imagePullSecrets }}
        - name: {{.}}{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: IfNotPresent
          image: {{ .Values.app.image }}
          resources:
            requests:
              memory: {{ .Values.app.limits.memory }}
              cpu: {{ .Values.app.limits.cpu }}
            limits:
              memory: {{ .Values.app.limits.memory }}
              cpu: {{ .Values.app.limits.cpu }}
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet:
              port: 3000
              path: /self/health/readiness
            initialDelaySeconds: 3
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: 3000
              path: /self/health/liveness
            initialDelaySeconds: 3
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              port: 3000
              path: /self/health/startup
            failureThreshold: 120
            periodSeconds: 1
            initialDelaySeconds: 1
            timeoutSeconds: 1
          env:
            - name: MEMORY_LIMIT_MB
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Chart.Name }}
                  resource: limits.memory
                  divisor: 1Mi
            - name: CPU_LIMIT_MILLISECONDS
              valueFrom:
                resourceFieldRef:
                  containerName: {{ .Chart.Name }}
                  resource: limits.cpu
                  divisor: 1m
            - name: MEMORY_THRESHOLD_PERCENT
              value: "{{ .Values.app.check.readiness.memoryPercentThreshold }}"
            - name: CHART_VERSION
              value: {{ .Chart.Version }}
