apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.app.service.port }}
      name: {{ .Values.app.name }}
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-{{ .Values.app.name }}
