{{ if .Values.mon.prometheus.installServiceMonitor -}}
{{ $Name := printf "%s-%s" .Release.Name .Chart.Name }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    instance: {{ $Name }}
    version: {{ .Chart.Version }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ $Name }}
  endpoints:
    - port: http
      path: /self/metrics
      interval: 10s
      scheme: http
{{- end }}