apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.app.service.port }}
      name: http
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ include "name" . }}
