{{ $Name := printf "%s-%s" .Release.Name .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.app.service.port }}
      name: http
      targetPort: 3000
      protocol: TCP
  selector:
    app: {{ $Name }}
