{{ if .Values.mon.prometheus.install -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    instance: {{ include "name" . }}
    version: {{ .Chart.Version }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
  endpoints:
    - port: http
      path: /self/metrics
      interval: 10s
      scheme: http
{{- end }}