app:
  replicaCount: 1
  image: terzey/web-svc:refactoring-2022-07-21T17-05-08
  service:
    port: 3000
  limits:
    memory: 100Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
infra:
  imagePullSecrets:
    - regcred
mon:
  prometheus:
    installServiceMonitor: true
