app:
  replicaCount: 1
  image: terzey/hello-nest:main-2022-07-18T16-47-21
  service:
    port: 3000
  limits:
    memory: 200Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
