app:
  replicaCount: 1
  image: terzey/hello-nest:main-2022-07-18T17-51-05
  service:
    port: 3000
  limits:
    memory: 100Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
