app:
  replicaCount: 1
  image: terzey/web-svc:main-2022-08-01T17-13-20
  service:
    port: 3000
  limits:
    memory: 200Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
infra:
  imagePullSecrets:
    - regcred
ingress:
  install: true
  className: nginx
  path: /api/v1(/|$)(.*)
  target: /api/$2
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75
  scaleDown:
    stabilizationWindowSeconds: 300
    percentage: 100
    periodSeconds: 15
  scaleUp:
    stabilizationWindowSeconds: 0
    percentage: 50
    pods: 2
    periodSeconds: 15
mon:
  prometheus:
    install: true
    alerting:
      memoryUsage:
        thresholdRatio: 0.85
        periodSeconds: 120
      cpuUsage:
        thresholdRatio: 0.85
        periodSeconds: 120
      eventloopLag:
        thresholdSeconds: 0.1
        periodSeconds: 10
      cpuCfsThrottled:
        thresholdRatio: 0.1
        periodSeconds: 120
      httpRequestDuration:
        thresholdSeconds: 1
        periodSeconds: 120
        quantile: 0.95 # should be one of src/metrics/metrics.ts#L7
  alertmanager:
    install: true
    config:
      matchLabels:
        alertmanagerConfig: 'true'
      groupWait: 10s
      groupInterval: 10s
      repeatInterval: 12h
      slackSecretAddress: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzUEtBM0JSTlovQjAzUURSSzVKRVQvMVRQb2VnVTN5RTk4SHNOWVlvWmhHeUtF
  grafana:
    install: true
    datasourceUid: PBFA97CFB590B2093
