app:
  replicaCount: 1
  image: terzey/hello-nest:add-ci-2022-07-18T17-34-31
  service:
    port: 3000
  limits:
    memory: 200Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
