app:
  replicaCount: 1
  image: terzey/web-svc:main-2022-07-31T08-32-39
  service:
    port: 3000
  limits:
    memory: 100Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
infra:
  imagePullSecrets:
    - regcred
mon:
  prometheus:
    install: true
    alerting:
      memoryUsage:
        thresholdRatio: 0.8
        periodSeconds: 120
      cpuUsage:
        thresholdRatio: 0.9
        periodSeconds: 120
      eventloopLag:
        thresholdSeconds: 0.1
        periodSeconds: 10
      cpuCfsThrottled:
        thresholdRatio: 0.1
        periodSeconds: 120
      httpRequestDuration:
        thresholdSeconds: 1
        periodSeconds: 120
        quantile: 0.95 # should be one of src/metrics/metrics.ts#L7
  alertmanager:
    install: true
    config:
      matchLabels:
        alertmanagerConfig: 'true'
      groupWait: 10s
      groupInterval: 10s
      repeatInterval: 12h
      slackSecretAddress: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzUEtBM0JSTlovQjAzUURSSzVKRVQvMVRQb2VnVTN5RTk4SHNOWVlvWmhHeUtF
  grafana:
    install: true
    datasourceUid: PBFA97CFB590B2093
