app:
  replicaCount: 1
  image: terzey/web-svc:add-alerting-rules-2022-07-23T13-25-17
  service:
    port: 3000
  limits:
    memory: 100Mi
    cpu: 200m
  check:
    readiness:
      memoryPercentThreshold: 90
infra:
  imagePullSecrets:
    - regcred
mon:
  prometheus:
    install: true
    alerting:
      memoryUsage:
        thresholdRatio: 0.8
        periodSeconds: 30
      cpuUsage:
        thresholdRatio: 0.9
        periodSeconds: 30
      eventloopLag:
        thresholdSeconds: 0.1
        periodSeconds: 10
      cpuCfsThrottled:
        thresholdRatio: 0.1
        periodSeconds: 30
      httpRequestDuration:
        thresholdSeconds: 1
        periodSeconds: 60
        quantile: 0.95 # should be one of src/metrics/metrics.ts#L7
