name: Build
on:
  push:
    paths:
      - src/**
      - package.json
      - Dockerfile
      - .github/workflows/build.yaml
env:
  IMAGE_NAME: terzey/web-svc
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install
        run: npm install
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: docker build . --file Dockerfile --tag "${IMAGE_NAME}"
