on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'package.json version'
        default: '0.0.1'
        required: true
      chartVersion:
        description: 'Chart.yaml version'
        default: '0.0.1'
        required: true
      branch:
        description: 'branch name'
        default: 'main'
        required: true
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.branch }}'
      - name: install jq
        run:  apt update && apt install -y jq
      - name: install yq
        run: apt install -y wget && wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod +x yq
