name: Publish
on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'package.json version'
        default: '0.0.1'
        required: true
      chartVersion:
        description: 'Chart.yaml version'
        default: '0.0.1'
        required: true
      branch:
        description: 'branch name'
        default: 'main'
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_PASSWORD:  ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.branch }}'
      - name: install jq
        run:  sudo apt update && sudo apt install -y jq
      - name: install yq
        run: |
          sudo apt install -y wget
          wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq
      - name: version package.json
        run: |
          jq '.version = "${{ github.event.inputs.appVersion }}"' package.json > package-1.json
          rm -f package.json
          mv package-1.json package.json
      - name: version helm/Chart.yaml
        run: |
          yq '.appVersion = "${{ github.event.inputs.appVersion }}"' helm/Chart.yaml | yq '.version = "${{ github.event.inputs.version }}"' > helm/Chart-1.yaml
          rm -f helm/Chart.yaml
          mv helm/Chart-1.yaml helm/Chart.yaml
      - name: docker login
        run: docker login --username terzey --password "${DOCKER_PASSWORD}"
      - name: docker build
        id: docker-image
        run: |
          IMAGE=terzey/hello-nest:"${{ github.event.inputs.branch }}-$(date +"%Y-%m-%dT%H-%M-%S")"
          #docker build . --file Dockerfile --tag "${IMAGE}"
          #docker push "${IMAGE}"
          echo "::set-output name=docker_image::${IMAGE}"
      - name: update helm/values.yaml
        run: |
          yq '.app.image = "${{ steps.docker-image.outputs.docker_image }}"' helm/values.yaml > helm/values-1.yaml
          rm -f helm/values.yaml
          mv helm/values-1.yaml helm/values.yaml
      - uses: peter-evans/create-pull-request@v4