name: Publish
on:
  workflow_dispatch:
    inputs:
      bumpChartSemver:
        description: helm/Chart.yaml semver to bump - it should be one of MAJOR, MINOR or PATCH
        default: PATCH
        required: true
      bumpAppSemver:
        description: package.json semver to bump - it should be one of MAJOR, MINOR or PATCH
        default: PATCH
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REPOSITORY_NAME: web-svc-dev
  REPOSITORY_URL: s3://k8s-helm-repository-bucket-dev/web-svc/charts
  IMAGE_NAME: terzey/web-svc
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Install yq
        run: |
          sudo apt install -y wget
          wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq

      - name: Install helm
        run: |
          wget -qO get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          bash get_helm.sh
          helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add helm repo
        run: helm repo add "${REPOSITORY_NAME}" "${REPOSITORY_URL}"

      - id: semver
        name: Update helm/Chart.yaml
        run: |
          bash bin/bump-semver.sh helm/Chart.yaml "${{ github.event.inputs.bumpChartSemver }}" package.json "${{ github.event.inputs.bumpAppSemver }}"
          echo "::set-output chart-version=$(yq '.version' helm/Chart.yaml)"
          echo "::set-output app-version=$(jq '.version' package.json)"

      - name: Docker login
        run: docker login --username terzey --password "${DOCKER_PASSWORD}"

      - name: Docker build
        id: docker-image
        run: |
          IMAGE=${IMAGE_NAME}:"${GITHUB_REF_NAME}-$(date +"%Y-%m-%dT%H-%M-%S")"
          docker build . --file Dockerfile --tag "${IMAGE}" --build-arg GITHUB_REF_NAME="${GITHUB_REF_NAME}" --build-arg GITHUB_SHA="${GITHUB_SHA:0:7}"
          docker push "${IMAGE}"
          echo "::set-output name=docker_image::${IMAGE}"
          echo "::set-output name=docker_image_size::$(docker image inspect ${IMAGE} --format='{{.Size}}')"

      - name: Update helm/values.yaml
        run: |
          yq '.app.image = "${{ steps.docker-image.outputs.docker_image }}"' helm/values.yaml > helm/values.yaml.tmp
          mv helm/values.yaml.tmp helm/values.yaml

      - name: Push helm chart
        run: |
          OUTPUT="$(helm package helm/)"
          RELEASE="$(echo "${OUTPUT}" | sed -E 's/Successfully packaged chart and saved it to: (.+)/\1/')"
          helm s3 push --relative "${RELEASE}" "${REPOSITORY_NAME}"

      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            package.json
            helm/Chart.yaml
            helm/values.yaml
          title: 'Publish helm/Chart.yaml version: ${{ steps.semver.outputs.chart-version }} appVersion: ${{ steps.semver.outputs.app-version }}'
          body: |
            Pushed docker image: ${{ steps.docker-image.outputs.docker_image }}
            Size: ${{ steps.docker-image.outputs.docker_image_size }} bytes
            Chart version: ${{ steps.semver.outputs.chart-version }}
            Application version: ${{ steps.semver.outputs.app-version }}

      - uses: pascalgn/automerge-action@v0.15.3
        name: Merge pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
