name: Publish Chart
on:
  workflow_dispatch:
    inputs:
      bumpChartSever:
        description: Chart.yaml semver to bump - it should be one of MAJOR, MINOR or PATCH
        default: PATCH
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPOSITORY_NAME: web-svc-dev
  REPOSITORY_URL: s3://k8s-helm-repository-bucket-dev/web-svc/charts
jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Install yq
        run: |
          sudo apt install -y wget
          wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq

      - name: Install helm
        run: |
          wget -qO get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          bash get_helm.sh
          helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Add repo
        run: helm repo add "${REPOSITORY_NAME}" "${REPOSITORY_URL}"

      - id: semver
        name: Update helm/Chart.yaml
        run: |
          bash bin/bump-semver.sh helm/Chart.yaml "${{ github.event.inputs.bumpChartSever }}"
          echo "::set-output version=$(yq '.version' helm/Chart.yaml)"

      - name: Push chart
        run: |
          OUTPUT="$(helm package helm/)"
          RELEASE="$(echo "${OUTPUT}" | sed -E 's/Successfully packaged chart and saved it to: (.+)/\1/')"
          helm s3 push --relative "${RELEASE}" "${REPOSITORY_NAME}"

      - id: pull-request
        name: Create pull-request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            helm/Chart.yaml
          body: |
            Chart version: ${{ steps.semver.outputs.version }}
          labels: automerge

      - uses: pascalgn/automerge-action@v0.15.3
        name: Merge pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

#      - uses: peter-evans/enable-pull-request-automerge@v2
#        name: Merge pull-request
#        with:
#          pull-request-number: ${{steps.pull-request.outputs.pull-request-number}}
#          token: ${{ secrets.TOKEN_GITHUB }}
