name: Publish
on:
  workflow_dispatch:
    inputs:
      chartVersion:
        description: 'Chart.yaml version'
        default: '0.0.1'
        required: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  REPOSITORY_NAME: hello-nest-dev
  REPOSITORY_URL: s3://k9s-helm-repository-bucket-dev/hello-nest/charts
jobs:
  Publish:
    runs-on: ubuntu-latest
    needs:
      - Install
    steps:
      - uses: actions/checkout@v3
      - name: install jq
        run: |
          sudo apt update
          sudo apt install -y jq
      - name: install yq
        run: |
          sudo apt install -y wget
          wget -qO yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod +x yq
      - name: version helm/Chart.yaml
        run: |
          yq '.appVersion = "${{ github.event.inputs.appVersion }}"' helm/Chart.yaml | yq '.version = "${{ github.event.inputs.chartVersion }}"' > helm/Chart-1.yaml
          rm -f helm/Chart.yaml
          mv helm/Chart-1.yaml helm/Chart.yaml
      - name: install helm
        run: |
          wget -qO get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          bash get_helm.sh
          helm plugin install https://github.com/hypnoglow/helm-s3.git
      - name: add repo
        run: helm repo add "${REPOSITORY_NAME}" "${REPOSITORY_URL}"
      - name: push chart
        run: |
          OUTPUT="$(helm package helm/)"
          RELEASE="$(echo "${OUTPUT}" | sed -E 's/Successfully packaged chart and saved it to: (.+)/\1/')"
          helm s3 push --relative "${RELEASE}" "${REPOSITORY_NAME}"
      - uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            helm/Chart.yaml
          body: |
            Chart version: ${{ github.event.inputs.chartVersion }}
